apiVersion: v1
items:
- apiVersion: cilium.io/v2
  kind: CiliumNetworkPolicy
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"cilium.io/v2","kind":"CiliumNetworkPolicy","metadata":{"annotations":{},"name":"dynamo-qwen-frontend-api","namespace":"ai-serving"},"spec":{"egress":[{"toEntities":["all"]}],"endpointSelector":{"matchLabels":{"app":"dynamo-qwen-frontend","model":"qwen3-14b-fp8"}},"ingress":[{"fromEntities":["cluster"],"toPorts":[{"ports":[{"port":"8000","protocol":"TCP"}],"rules":{"http":[{"path":"/v1/.*"},{"path":"/metrics"},{"path":"/health"},{"path":"/live"}]}}]},{"fromEntities":["host","remote-node"]},{"fromCIDR":["192.168.200.8/32"],"toPorts":[{"ports":[{"port":"8000","protocol":"TCP"}],"rules":{"http":[{"headerMatches":[{"name":"Authorization","secret":{"name":"vllm-api-token","namespace":"ai-serving"}}],"path":"/v1/.*"}]}}]},{"fromCIDRSet":[{"cidr":"0.0.0.0/0","except":["192.168.200.8/32"]}],"toPorts":[{"ports":[{"port":"8000","protocol":"TCP"}],"rules":{"http":[{"path":"/v1/.*"}]}}]}]}}
    creationTimestamp: "2026-07-23T03:11:08Z"
    generation: 4
    name: dynamo-qwen-frontend-api
    namespace: ai-serving
    resourceVersion: "2031507122"
    uid: 68a7a67c-6472-490c-b8fb-007cd8ac8c7e
  spec:
    egress:
    - toEntities:
      - all
    endpointSelector:
      matchLabels:
        app: dynamo-qwen-frontend
        model: qwen3-14b-fp8
    ingress:
    - fromEntities:
      - cluster
      toPorts:
      - ports:
        - port: "8000"
          protocol: TCP
        rules:
          http:
          - path: /v1/.*
          - path: /metrics
          - path: /health
          - path: /live
    - fromEntities:
      - host
      - remote-node
    - fromCIDR:
      - 192.168.200.8/32
      toPorts:
      - ports:
        - port: "8000"
          protocol: TCP
        rules:
          http:
          - headerMatches:
            - name: Authorization
              secret:
                name: vllm-api-token
                namespace: ai-serving
            path: /v1/.*
    - fromCIDRSet:
      - cidr: 0.0.0.0/0
        except:
        - 192.168.200.8/32
      toPorts:
      - ports:
        - port: "8000"
          protocol: TCP
        rules:
          http:
          - path: /v1/.*
  status:
    conditions:
    - lastTransitionTime: "2026-07-23T03:11:08Z"
      message: Policy validation succeeded
      status: "True"
      type: Valid
- apiVersion: cilium.io/v2
  kind: CiliumNetworkPolicy
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"cilium.io/v2","kind":"CiliumNetworkPolicy","metadata":{"annotations":{},"name":"vllm-http-visibility","namespace":"ai-serving"},"spec":{"enableDefaultDeny":{"egress":false,"ingress":false},"endpointSelector":{"matchLabels":{"app":"vllm"}},"ingress":[{"fromEntities":["cluster"],"toPorts":[{"ports":[{"port":"8000","protocol":"TCP"}],"rules":{"http":[{}]}}]},{"fromCIDRSet":[{"cidr":"0.0.0.0/0","except":["192.168.200.8/32"]}],"toPorts":[{"ports":[{"port":"8000","protocol":"TCP"}],"rules":{"http":[{}]}}]}]}}
    creationTimestamp: "2025-12-31T05:38:16Z"
    generation: 1
    name: vllm-http-visibility
    namespace: ai-serving
    resourceVersion: "1063811472"
    uid: 8a76515b-774b-44ca-9127-40d9fd6cf958
  spec:
    enableDefaultDeny:
      egress: false
      ingress: false
    endpointSelector:
      matchLabels:
        app: vllm
    ingress:
    - fromEntities:
      - cluster
      toPorts:
      - ports:
        - port: "8000"
          protocol: TCP
        rules:
          http:
          - {}
    - fromCIDRSet:
      - cidr: 0.0.0.0/0
        except:
        - 192.168.200.8/32
      toPorts:
      - ports:
        - port: "8000"
          protocol: TCP
        rules:
          http:
          - {}
  status:
    conditions:
    - lastTransitionTime: "2025-12-31T05:38:16Z"
      message: Policy validation succeeded
      status: "True"
      type: Valid
- apiVersion: cilium.io/v2
  kind: CiliumNetworkPolicy
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"cilium.io/v2","kind":"CiliumNetworkPolicy","metadata":{"annotations":{},"name":"vllm-token-from-lb","namespace":"ai-serving"},"spec":{"egress":[{"toEndpoints":[{"matchLabels":{"k8s:io.kubernetes.pod.namespace":"kube-system","k8s:k8s-app":"kube-dns"}}],"toPorts":[{"ports":[{"port":"53","protocol":"UDP"},{"port":"53","protocol":"TCP"}],"rules":{"dns":[{"matchPattern":"*"}]}}]},{"toEndpoints":[{"matchLabels":{"k8s:io.kubernetes.pod.namespace":"kube-system","k8s:k8s-app":"coredns"}}],"toPorts":[{"ports":[{"port":"53","protocol":"UDP"},{"port":"53","protocol":"TCP"}],"rules":{"dns":[{"matchPattern":"*"}]}}]},{"toEntities":["all"]}],"endpointSelector":{"matchLabels":{"app":"vllm"}},"ingress":[{"fromCIDR":["192.168.200.8/32"],"toPorts":[{"ports":[{"port":"8000","protocol":"TCP"}],"rules":{"http":[{"headerMatches":[{"name":"Authorization","secret":{"name":"vllm-api-token","namespace":"ai-serving"}}],"path":"/v1/.*"}]}}]},{"fromEntities":["cluster"]},{"fromCIDRSet":[{"cidr":"0.0.0.0/0","except":["192.168.200.8/32"]}]}]}}
    creationTimestamp: "2025-12-07T05:57:42Z"
    generation: 2
    name: vllm-token-from-lb
    namespace: ai-serving
    resourceVersion: "992701920"
    uid: 021f6d9d-ee75-49bd-aa89-c11cd0cb0fbc
  spec:
    egress:
    - toEndpoints:
      - matchLabels:
          k8s:io.kubernetes.pod.namespace: kube-system
          k8s:k8s-app: kube-dns
      toPorts:
      - ports:
        - port: "53"
          protocol: UDP
        - port: "53"
          protocol: TCP
        rules:
          dns:
          - matchPattern: '*'
    - toEndpoints:
      - matchLabels:
          k8s:io.kubernetes.pod.namespace: kube-system
          k8s:k8s-app: coredns
      toPorts:
      - ports:
        - port: "53"
          protocol: UDP
        - port: "53"
          protocol: TCP
        rules:
          dns:
          - matchPattern: '*'
    - toEntities:
      - all
    endpointSelector:
      matchLabels:
        app: vllm
    ingress:
    - fromCIDR:
      - 192.168.200.8/32
      toPorts:
      - ports:
        - port: "8000"
          protocol: TCP
        rules:
          http:
          - headerMatches:
            - name: Authorization
              secret:
                name: vllm-api-token
                namespace: ai-serving
            path: /v1/.*
    - fromEntities:
      - cluster
    - fromCIDRSet:
      - cidr: 0.0.0.0/0
        except:
        - 192.168.200.8/32
  status:
    conditions:
    - lastTransitionTime: "2025-12-07T05:57:42Z"
      message: Policy validation succeeded
      status: "True"
      type: Valid
kind: List
metadata:
  resourceVersion: ""
