apiVersion: v1
data:
  config.json: |
    {
      "periodicUpdateInterval": 300,
      "configList": [
        {
          "resourceName": "ib",
          "resourcePrefix": "rdma",
          "rdmaHcaMax": 1,
          "selectors": {
            "vendors": ["15b3"],
            "deviceIDs": ["1021"],
            "drivers": ["mlx5_core"],
            "linkTypes": ["ether"]
          }
        }
      ]
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.json":"{\n  \"periodicUpdateInterval\": 300,\n  \"configList\": [\n    {\n      \"resourceName\": \"ib\",\n      \"resourcePrefix\": \"rdma\",\n      \"rdmaHcaMax\": 1,\n      \"selectors\": {\n        \"vendors\": [\"15b3\"],\n        \"deviceIDs\": [\"1021\"],\n        \"drivers\": [\"mlx5_core\"],\n        \"linkTypes\": [\"ether\"]\n      }\n    }\n  ]\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"rdma-devices","namespace":"kube-system"}}
  creationTimestamp: "2026-07-23T03:02:15Z"
  name: rdma-devices
  namespace: kube-system
  resourceVersion: "2030662629"
  uid: add230c6-ab9e-4b1d-8466-f3df5c187e54
