network:
  version: 2
  renderer: NetworkManager
  ethernets:
    ens65np0:
      match:
        macaddress: a0:88:c2:34:e7:f6
      dhcp4: false
      dhcp6: false
      addresses:
      - 172.31.230.113/24
      mtu: 9000
      optional: true
      link-local: []
